version: '3.7'
networks: 
  az_docker_network: 
    driver: bridge
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    container_name: docker_php
    working_dir: "/var/www/muonphuong"
    networks: 
      - az_docker_network
    volumes: 
      - "../:/var/www/muonphuong"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: docker_nginx
    working_dir: "/var/www/muonphuong"
    networks: 
      - az_docker_network
    volumes: 
      - "../:/var/www/muonphuong"
      - "./nginx/:/etc/nginx/conf.d/"
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Az#86*123
    ports:
      - "3306:3306"
    container_name: az_docker_mariadb
    volumes:
      - "./mariadb/data-mariadb:/var/lib/mysql"
    networks:
      - az_docker_network
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes: 
      - "./redis/cache:/data"
    container_name: docker_redis
    restart: always
    networks: 
      - az_docker_network
    ports:
      - "6379:6379"      
  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Admin@12345
    ports:
      - "1433:1433"
    container_name: docker_sqlserver
    networks: 
      - az_docker_network
    volumes:
      - "ms-sqlserver-data:/var/opt/mssql"
volumes:
  ms-sqlserver-data:
    driver: local